### PR TITLE
Small bugfixes

### PR DESCRIPTION
**Pull request by clickbuster**
The `finally()` call of the hook, caused a Warning, since it wasn't returning anything during emit, which is now fixed, also added some common gitignore exceptions.

### CODE REVIEW

**Comment by luislobo** [comment]
It would also need `return true;` after line 35: `sails.log.error('Got error with ' + name + ' fixture: ' + err);`
That will fix `Warning: a promise was created in a handler but was not returned from it`

**Comment by luislobo** [comment]
+1

**Comment by luislobo** [comment]
@arryon Are you still maintaining this project? I'm asking so that if not, I'll move ahead and publish a different package and maintain it. Thank you!

**Comment by arryon** [comment]
Hi @luislobo! I'm currently not actively using this repo and don't really have the motivation to maintain it anymore. If you are open to it, we could also arrange ownership transference instead of you publishing a different package. Please let me know.

**Comment by luislobo** [comment]
@arryon Sure, we use it here everyday, so, if you are up to, I'd be glad to maintain it.

**Pull request merged**
